epochs: [100]
lr_scheduler_min: [1e-5]
lr_scheduler_patience: ["105"]
lr_scheduler: ["ReduceLROnPlateau"]
lr_scheduler_decay_rate: [0.5]

model: ["GIN"]
batch_size: [128]

device: [0]
train_eval_period: [1]

model: ["embed_sparse_cin"]
use_coboundaries: ["True"]
indrop_rate: [0.0]
drop_rate: [0.5]
drop_position: ["lin2"]
graph_norm: ["bn"]
nonlinearity: ["relu"]
final_readout: ["sum"]
init_method: ["sum"]
readout: ["mean"]
lr:  [0.001]
max_dim: [2] 
max_ring_size: [6]
emb_dim: [256]
num_layers: [3]
num_workers: [1]
preproc_jobs: [1]
use_edge_features: [""]
dump_curves: [""]
early_stop: [""]