epochs: [500]
virtual_node: [0]
tracking: [0]

batch_size: [64]
lr:  [0.001]
lr_schedule_patience: [20]
lr_scheduler: ["ReduceLROnPlateau"]
lr_scheduler_decay_rate: [0.5]
lr_schedule_patience: [20]
min_lr: [1e-5]

model: ["GIN"]
emb_dim: [256, 512]
drop_out: [0.5]
num_layer: [3, 4, 5]
pooling: ["sum", "mean"]

policy: ["ego_nets"]
num_hops: [3]
expl_type_enc: [1]
dim_pooling: [1]
dss_message_passing: [1]