epochs: [100]
lr_scheduler_min: [0]
lr_scheduler_patience: ["101"]
lr_scheduler: ["ReduceLROnPlateau"]

model: ["GIN"]
batch_size: [32]

device: [0]
train_eval_period: [1]

model: ["ogb_embed_sparse_cin"]
use_coboundaries: ["True"]
indrop_rate: [0.0]
drop_rate: [0.5]
drop_position: ["lin2"]
graph_norm: ["bn"]
nonlinearity: ["relu"]
final_readout: ["sum", "mean"]
init_method: ["sum"]
readout: ["mean"]
lr: [0.001, 0.0001]
max_dim: [2] 
max_ring_size: [6]
emb_dim: [64, 256]
num_layers: [1,2,3]
num_workers: [0]
preproc_jobs: [1]
use_edge_features: [""]
dump_curves: [""]
early_stop: [""]