epochs: [350]
batch_size: [12]
emb_dim: [160]
drop_out: [0]
dim_pooling: [0]
num_layer: [3]
max_struct_size: [8]
aggr_edge_atr: [0]
aggr_vertex_feat: [0]
lr:  [5e-4]
expl_type_enc: [1]
virtual_node: [0]
lr_schedule_patience: [20]
rings: [1]
tracking: [1]
min_lr: [1e-6]
node_encoder: [0]


