epochs: [350]
batch_size: [8]
emb_dim: [64]
drop_out: [0]
dim_pooling: [0]
num_layer: [4]
aggr_edge_atr: [0]
aggr_vertex_feat: [0]
lr:  [5e-4]
expl_type_enc: [1]
node_encoder: [0]
virtual_node: [0]
rings: [0]
tracking: [1]
policy: ["ego_nets"]
esan: [0]
num_hops: [4]
pooling: ["mean"]
min_lr: [1e-6]
lr_schedule_patience: [5]

